---
- name: Start docker node exporter container
  community.docker.docker_compose:
    state: present
    project_name: prometheus_blackbox_exporter
    definition:
      version: '2'
      services:
        blackbox_exporter:
          image: "{{ IPMI_exporter_docker_image }}"
          container_name: "{{ IPMI_exporter_container_name }}"
          ports:
            - "127.0.0.1:{{ IPMI_exporter_host_port }}:{{ IPMI_exporter_host_port }}"
          hostname: "{{ ansible_host }}"
          restart: always
          labels: "{{ IPMI_exporter_docker_labels }}"
