---
- name: Environment variable example
  hosts: all
  
  vars: 
    command: curl ifconfig.me
  tasks:
    - name: Ansible Shell module set an environment variable
      shell: " {{ command }}"
      warn: false
      register: command_result
    - debug: 
        msg: " {{ my_name }} ip-adress- {{ command_result.stdout }}"

